name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup JDK with GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'liberica'
          java-package: 'jdk'
          java-version: '23'
          cache: 'gradle'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build
        run: ./gradlew build nativeCompile --no-daemon
